### ISSUE TITLE
Could not resolve dependencies: platform v. 8.0.2

### ISSUE THREAD

**Issue by tuborgman** [Euterpea/HSoM#6]
It seems that HSoM cannot be installed

$ cabal install
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: HSoM-1.0.0 (user goal)
trying: StateVar-1.1.0.4/installed-5dJ... (dependency of
GLUT-2.7.0.12/installed-KMb...)
next goal: heap (dependency of HSoM-1.0.0)
rejecting: heap-0.6.0/installed-52d... (conflict: HSoM => heap>=1.0 && <2.0)
trying: heap-1.0.3
next goal: Euterpea (dependency of HSoM-1.0.0)
rejecting: Euterpea-2.0.2/installed-H2X... (conflict: heap==1.0.3, Euterpea =>
heap==0.6.0/installed-52d...)
rejecting: Euterpea-2.0.2, Euterpea-2.0.1, Euterpea-2.0.0 (conflict: StateVar
=> stm==2.4.4.1/installed-JQn..., Euterpea => stm==2.4.2)
rejecting: Euterpea-1.1.1, Euterpea-1.1.0, Euterpea-1.0.0 (conflict: HSoM =>
Euterpea>=2.0)
Backjump limit reached (currently 2000, change with --max-backjumps or try to
run with --reorder-goals).

-- 
cabal-install version 1.24.0.2
compiled using version 1.24.2.0 of the Cabal library

The Glorious Glasgow Haskell Compilation System, version 8.0.2

OS: macOS Sierra 10.12.5
Haskell Platform: 8.0.2 Full

**Comment by donya** [comment]
Please use the development version of Euterpea on GitHub (version 2.0.3) and try again.

**Comment by wlmr** [comment]
I have a similar issue so I guess I should write it here. I installed the development version of Euterpea and then tried installing HSoM again but Im still getting the same error..

$ cabal install
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: HSoM-1.0.0 (user goal)
next goal: Euterpea (dependency of HSoM-1.0.0)
rejecting: Euterpea-2.0.2/installed-Iz3..., Euterpea-1.1.2/installed-LOQ...,
Euterpea-2.0.2, Euterpea-2.0.1, Euterpea-2.0.0, Euterpea-1.1.1,
Euterpea-1.1.0, Euterpea-1.0.0 (conflict: HSoM => Euterpea>=2.0.3)
Dependency tree exhaustively searched.

OS: Arch
cabal-install version 1.24.0.2

**Comment by donya** [comment]
I get no errors on completely clean installs (fresh install of Haskell Platform, etc.) as of this afternoon when testing after I updated HSoM. The errors you're getting suggest you are not using the 2.0.3 requirement fix I pushed today since it is still looking for older versions on Hackage. Try using ghc-pkg unlist to remove any installed versions of Euterpea and HSoM, then downloading the most recent versions of each from GitHub and trying again.

**Comment by wlmr** [comment]
As I am still quite new to the whole open source community I always get blown away by the helpfulness of some of its people. I reinstalled the packages with ghc-pkg unregister and it worked. Btw the link to the Euterpea repo under "OPTIONAL: Obtaining the Development Version from GitHub"  [here](http://www.euterpea.com/download-and-installation/) isn't working. Thank you, Donya. You are an inspiration.

**Comment by donya** [comment]
Thanks for the dead link notice - should be fixed now.

Euterpea 2.0.3 is now on Hackage, so the HSoM dependency issue should be resolved now with a "cabal update" before installing things. For those who already installed the GitHub version of Euterpea as a work-around this week, there is no need to do anything else currently since the Hackage and GitHub versions are identical right now (both 2.0.3).

HSoM will be going on Hackage very soon too.
